### ISSUE TITLE
task4有bug

### ISSUE THREAD

**Issue by HXYstudy** [Alic-yuan/nlp-beginner-finish#11]
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    cn.train()
  File "main.py", line 71, in train
    loss = model.log_likelihood(X,y)
  File "/content/drive/My Drive/fudanlp/nlp-beginner-finish-master/task4/model/LSTM_CRF.py", line 40, in log_likelihood
    x = x.transpose(0,1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by HXYstudy** [comment]
或许是我的某些库版本和您的不太一样，能否把运行所需要的库的版本给出说明呢

**Comment by iwanttoknowmore** [comment]
你好，请问你这个问题解决了吗

**Comment by wencan** [comment]
遇到同样的问题 
python 3.8
torch 2.1.2
